version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-v2-{{ checksum "yarn.lock" }}
            - dependency-cache-v2-
      - run:
          name: Install Dependencies
          command: NODE_ENV=development yarn --frozen-lockfile
      - save_cache:
          key: dependency-cache-v2-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: NODE_ENV=production yarn build
      - run:
          name: Deploy
          command: yarn deploy